#!/usr/bin/env bash
# ===========================================================================
# run_synth.sh -- drive the LUT4 + DSP synthesis flow over the example designs.
#
#   ./run_synth.sh                  # every design
#   ./run_synth.sh -d mac_8         # one design
#   ./run_synth.sh -d all           # same as no argument
#   ./run_synth.sh --no-sim         # structural checks only, skip iverilog
#   ./run_synth.sh --keep-going     # do not stop at the first failing design
#
# Needs `yosys` and `iverilog` on PATH. On this setup they live in the multipass
# VM, not on the macOS host, so run it there:
#
#   ssh ubuntu@<vm-ip> 'cd ~/share/IFT/lut4_dsp_synth && ./run_synth.sh'
#
# For each design it produces, under out/<design>/:
#   <design>.ys                 the concrete Yosys script, re-runnable by hand
#   <design>_lut4_dsp.v         Verilog netlist  (lut4 + mult_8 + $_DFF_P_)
#   <design>_lut4_dsp.blif      BLIF netlist, EBLIF flavour (.subckt + .param)
#   <design>.eblif              copy of the above under the name IFT expects
#   <design>_lut4_dsp.json      JSON netlist, used by the structural checker
#   <design>_stat.txt           Yosys `stat` before and after LUT4 mapping
#   <design>_yosys.log          full Yosys transcript
#   <design>_sim.log            iverilog transcript
# ===========================================================================
set -u -o pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Run everything from this directory and refer to files RELATIVELY.
#
# Not cosmetic. Yosys builds autogenerated net names out of the source file
# path, so an absolute path puts the build machine's directory layout inside
# the netlists -- names like
#   $techmap$add$/home/ubuntu/share/IFT/lut4_dsp_synth/examples/mac_8.v:16$2...
# which makes the BLIF differ between machines for no functional reason, and
# lands those paths in IFT's variable names, since IFT uses BLIF net names
# directly. Relative paths give `$techmap$add$examples/mac_8.v:16$2...`.
cd "$HERE" || exit 1

SCRIPTS="scripts"
EXAMPLES="examples"
VERIFY="verify"
OUT="out"

LUT_SIZE=4

# The DSP mapping parameters handed to +/mul2dsp.v. MAXWIDTH is the primitive's
# real size; MINWIDTH is the policy knob -- multiplies narrower than this are
# left in soft logic on purpose. Both defaults are OpenFPGA's own, from
# openfpga_flow/tasks/fpga_verilog/dsp/single_mode_mult_8x8/config/task.conf.
DSP_A_MAXWIDTH=8
DSP_B_MAXWIDTH=8
DSP_A_MINWIDTH=2
DSP_B_MINWIDTH=2
DSP_NAME=mult_8x8      # the techmap intermediary; the real cell is mult_8

# ---------------------------------------------------------------------------
# Design table.
#
# One line per design:  <name> <top_module> <expect_dsp> <expect_lut>
#
# expect_dsp is an exact count and expect_lut is zero|nonzero|any. These are
# MEASURED values, not aspirations -- the point of asserting them is that a
# regression which quietly stops preserving DSPs cannot hide behind a passing
# simulation. If you change the flow and a count moves, work out why before
# you update the number.
# ---------------------------------------------------------------------------
DESIGNS=(
  "mult_8x8_infer     mult_8x8_infer     1  any"
  "mac_8              mac_8              1  nonzero"
  "mult_16x16_split   mult_16x16_split   4  nonzero"
  "mult_direct_inst   mult_direct_inst   1  nonzero"
  "mac_8_pipelined    mac_8_pipelined    1  nonzero"
  "dsp_datapath       dsp_datapath       2  nonzero"
  "mult_1x1_soft      mult_1x1_soft      0  nonzero"
  "mult_signed_8x8    mult_signed_8x8    0  nonzero"
)

RUN_SIM=1
KEEP_GOING=0
WANT="all"

while [ $# -gt 0 ]; do
  case "$1" in
    -d|--design) WANT="$2"; shift 2 ;;
    --no-sim)    RUN_SIM=0; shift ;;
    --keep-going) KEEP_GOING=1; shift ;;
    -h|--help)   sed -n '2,30p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

command -v yosys >/dev/null || { echo "ERROR: yosys not on PATH" >&2; exit 1; }
if [ "$RUN_SIM" = 1 ]; then
  command -v iverilog >/dev/null || {
    echo "ERROR: iverilog not on PATH (use --no-sim to skip simulation)" >&2
    exit 1; }
fi

echo "yosys:    $(yosys -V 2>/dev/null | head -1)"
[ "$RUN_SIM" = 1 ] && echo "iverilog: $(iverilog -V 2>/dev/null | head -1)"
echo

# ---------------------------------------------------------------------------
run_one() {
  local name="$1" top="$2" expect_dsp="$3" expect_lut="$4"
  local dir="$OUT/$name"
  local src="$EXAMPLES/$name.v"
  local tb="$VERIFY/tb_$name.v"

  [ -f "$src" ] || { echo "  ERROR: missing source $src"; return 1; }

  rm -rf "$dir"; mkdir -p "$dir"

  local ys="$dir/$name.ys"
  local out_v="$dir/${name}_lut4_dsp.v"
  local out_blif="$dir/${name}_lut4_dsp.blif"
  local out_json="$dir/${name}_lut4_dsp.json"
  local out_stat="$dir/${name}_stat.txt"

  # Substitute the template. `|` as the sed delimiter so paths with `/` are fine.
  sed -e "s|\${VERILOG_FILES}|$src|g" \
      -e "s|\${TOP_MODULE}|$top|g" \
      -e "s|\${CELLS_SIM}|$SCRIPTS/cells_sim.v|g" \
      -e "s|\${DSP_MAP}|$SCRIPTS/dsp_map.v|g" \
      -e "s|\${LUT_MAP}|$SCRIPTS/map_lut_to_lut4.v|g" \
      -e "s|\${DSP_PARAMS}|-D DSP_A_MAXWIDTH=$DSP_A_MAXWIDTH -D DSP_B_MAXWIDTH=$DSP_B_MAXWIDTH -D DSP_A_MINWIDTH=$DSP_A_MINWIDTH -D DSP_B_MINWIDTH=$DSP_B_MINWIDTH -D DSP_NAME=$DSP_NAME|g" \
      -e "s|\${LUT_SIZE}|$LUT_SIZE|g" \
      -e "s|\${OUTPUT_VERILOG}|$out_v|g" \
      -e "s|\${OUTPUT_BLIF}|$out_blif|g" \
      -e "s|\${OUTPUT_JSON}|$out_json|g" \
      -e "s|\${OUTPUT_STAT}|$out_stat|g" \
      "$SCRIPTS/lut4_dsp.ys.tmpl" > "$ys"

  # Any placeholder left on an executable (non-comment) line means the table
  # above and the template have drifted apart. Comment lines are exempt: the
  # template documents its own placeholders, and a comment cannot break Yosys.
  if grep -vE '^[[:space:]]*(#|$)' "$ys" | grep -q '\${'; then
    echo "  ERROR: unsubstituted placeholder left in $ys:"
    grep -nE '\$\{' "$ys" | grep -vE ':[[:space:]]*#' | sed 's/^/      /'
    return 1
  fi

  if ! yosys -s "$ys" > "$dir/${name}_yosys.log" 2>&1; then
    echo "  ERROR: yosys failed -- tail of $dir/${name}_yosys.log:"
    tail -25 "$dir/${name}_yosys.log" | sed 's/^/      /'
    return 1
  fi

  for f in "$out_v" "$out_blif" "$out_json"; do
    [ -s "$f" ] || { echo "  ERROR: $f was not written (or is empty)"; return 1; }
  done

  # The name and extension IFT's src/EBLIF.py expects.
  cp "$out_blif" "$dir/$name.eblif"

  # ---- structural checks -------------------------------------------------
  if ! python3 "$SCRIPTS/check_netlist.py" \
        --json "$out_json" --blif "$out_blif" --top "$top" \
        --expect-dsp "$expect_dsp" --expect-lut "$expect_lut" \
        | sed 's/^/  /'; then
    return 1
  fi

  # ---- functional check --------------------------------------------------
  if [ "$RUN_SIM" = 1 ]; then
    [ -f "$tb" ] || { echo "  ERROR: missing testbench $tb"; return 1; }
    local sim="$dir/${name}_sim"
    # simcells_dff.v is simulation-only: it models Yosys' internal $_DFF_P_,
    # which iverilog does not know. See the comment at the head of that file.
    if ! iverilog -g2005 -o "$sim" \
          "$tb" "$out_v" "$SCRIPTS/cells_sim.v" "$SCRIPTS/simcells_dff.v" \
          > "$dir/${name}_sim.log" 2>&1; then
      echo "  ERROR: iverilog compile failed -- see $dir/${name}_sim.log"
      tail -20 "$dir/${name}_sim.log" | sed 's/^/      /'
      return 1
    fi
    "$sim" >> "$dir/${name}_sim.log" 2>&1
    # Absence of a PASS line is a failure too -- a testbench that died early
    # prints neither PASS nor FAIL, and must not be read as success.
    if ! grep -q "SIM PASS" "$dir/${name}_sim.log"; then
      echo "  ERROR: simulation did not report PASS:"
      grep -E "SIM (PASS|FAIL)|MISMATCH|ERROR" "$dir/${name}_sim.log" \
        | head -12 | sed 's/^/      /'
      [ -s "$dir/${name}_sim.log" ] || echo "      (empty simulation log)"
      return 1
    fi
    grep -E "SIM PASS|coverage" "$dir/${name}_sim.log" | sed 's/^/  /'
  fi

  return 0
}

# ---------------------------------------------------------------------------
declare -a ROWS=()
FAILED=0
RAN=0

for entry in "${DESIGNS[@]}"; do
  set -- $entry
  name="$1"; top="$2"; edsp="$3"; elut="$4"
  if [ "$WANT" != "all" ] && [ "$WANT" != "$name" ]; then continue; fi

  echo "=== $name (top=$top, expect dsp=$edsp lut4=$elut) ==="
  RAN=$((RAN + 1))
  if run_one "$name" "$top" "$edsp" "$elut"; then
    ROWS+=("$name|ok")
  else
    ROWS+=("$name|FAIL")
    FAILED=$((FAILED + 1))
    [ "$KEEP_GOING" = 1 ] || { echo; echo "stopping at first failure (use --keep-going to continue)"; break; }
  fi
  echo
done

if [ "$RAN" = 0 ]; then
  echo "ERROR: no design matched '$WANT'. Known designs:" >&2
  for entry in "${DESIGNS[@]}"; do set -- $entry; echo "  $1" >&2; done
  exit 2
fi

# ---------------------------------------------------------------------------
echo "======================================================================"
printf "%-20s %-8s %6s %6s %5s\n" DESIGN RESULT DSP LUT4 DFF
echo "----------------------------------------------------------------------"
for row in "${ROWS[@]}"; do
  name="${row%%|*}"; verdict="${row##*|}"
  json="$OUT/$name/${name}_lut4_dsp.json"
  if [ -s "$json" ]; then
    read -r d l f < <(python3 - "$json" <<'PY'
import json,sys
mods=json.load(open(sys.argv[1]))["modules"]
# The top module is the one that is not a blackbox.
c={}
for m in mods.values():
    if m.get("attributes",{}).get("blackbox"): continue
    for cell in m.get("cells",{}).values():
        c[cell["type"]]=c.get(cell["type"],0)+1
print(c.get("mult_8",0), c.get("lut4",0), c.get("$_DFF_P_",0))
PY
)
  else
    d="-"; l="-"; f="-"
  fi
  printf "%-20s %-8s %6s %6s %5s\n" "$name" "$verdict" "$d" "$l" "$f"
done
echo "======================================================================"

if [ "$FAILED" = 0 ]; then
  echo "ALL $RAN DESIGN(S) OK"
  exit 0
fi
echo "$FAILED of $RAN DESIGN(S) FAILED"
exit 1
